remuneration:
    path: /
    controller: App\Controller\RemunerationController::ChoixRemun


#sujet:
#    path: /
 #   controller: App\Controller\SujetController::add


#index:
#    path: /
#    controller: App\Controller\DefaultController::index
